export const DEMO_INVESTIGATION_DATA = {
  analysis_id: null,
  ai_status: "active",
  integrity_hash: "8b9f86b8b5ab6dcfe5b95d04f5e91c2fbf1c4b9ab2a4d90f6e3ec6f2b4d10f7e",
  sealed_at: "2026-03-01T10:20:30Z",
  generated_at: "2026-03-01T10:20:30Z",
  summary: {
    total_accounts_analyzed: 9613,
    suspicious_accounts_flagged: 14,
    fraud_rings_detected: 3,
    processing_time_seconds: 10.7,
  },
  suspicious_accounts: [
    {
      account_id: "MERCHANT_01",
      suspicion_score: 94.2,
      detected_patterns: ["fan_in", "high_velocity"],
      pattern_labels: ["fan_in", "high_velocity"],
      ring_id: "RING-02",
      financial_role: "CONTROLLER",
      victim_probability: 0.04,
      mule_probability: 0.21,
      controller_probability: 0.75,
      explanation: "Primary aggregation hub with high fan-in and burst activity.",
      ai_source: "demo",
    },
    {
      account_id: "ACC_00123",
      suspicion_score: 81.4,
      detected_patterns: ["cycle_length_3"],
      pattern_labels: ["cycle_length_3"],
      ring_id: "RING-01",
      financial_role: "MULE",
      victim_probability: 0.08,
      mule_probability: 0.72,
      controller_probability: 0.2,
      explanation: "Node participates in repeated circular transfer paths.",
      ai_source: "demo",
    },
    {
      account_id: "ACC_00345",
      suspicion_score: 67.8,
      detected_patterns: ["shell_chain"],
      pattern_labels: ["shell_chain"],
      ring_id: "RING-03",
      financial_role: "MULE",
      victim_probability: 0.13,
      mule_probability: 0.66,
      controller_probability: 0.21,
      explanation: "Intermediary hop in a layered shell-chain structure.",
      ai_source: "demo",
    },
    {
      account_id: "ACC_00891",
      suspicion_score: 44.6,
      detected_patterns: ["fan_out"],
      pattern_labels: ["fan_out"],
      ring_id: null,
      financial_role: "POSSIBLE_VICTIM",
      victim_probability: 0.61,
      mule_probability: 0.26,
      controller_probability: 0.13,
      explanation: "Outflow profile suggests possible compromised endpoint.",
      ai_source: "demo",
    },
  ],
  fraud_rings: [
    {
      ring_id: "RING-01",
      pattern_type: "cycle_length_3",
      member_accounts: ["ACC_00123", "ACC_00642", "ACC_00417"],
      risk_score: 86.1,
    },
    {
      ring_id: "RING-02",
      pattern_type: "fan_in",
      member_accounts: ["MERCHANT_01", "MULE_01", "MULE_02", "MULE_03"],
      risk_score: 93.4,
    },
    {
      ring_id: "RING-03",
      pattern_type: "shell_chain",
      member_accounts: ["SOURCE_07", "ACC_00345", "SHELL_2", "END_PT"],
      risk_score: 68.8,
    },
  ],
  ai_explanations: [
    {
      account_id: "MERCHANT_01",
      explanation: "Primary aggregation hub with high fan-in and burst activity.",
    },
    {
      account_id: "ACC_00123",
      explanation: "Node participates in repeated circular transfer paths.",
    },
    {
      account_id: "ACC_00345",
      explanation: "Intermediary hop in a layered shell-chain structure.",
    },
    {
      account_id: "ACC_00891",
      explanation: "Outflow profile suggests possible compromised endpoint.",
    },
  ],
};
